### ISSUE TITLE
allow for children without spouses

### ISSUE THREAD

**Issue by marwahaha** [ErikGartner/dTree#43]
Hi Erik, cool library!

There is a significant amount of divorce in my family. I'm looking for a way to represent divorce, or ex-spouses, or children with only one parent.

Let me know how we could build this, and I'm happy to help.

Kunal

**Comment by ErikGartner** [comment]
Hey!

Children with one parent is very possible since a node can have a "children" attribute directly, i.e. not inside a marriages attribute. Also ex-spouses is possible since the attribute "marriages" takes an array of marriages.

Drawing multiple marriages is not always super pretty and could possibly be improved though. 

Does this answer your questions?

/Erik

**Comment by marwahaha** [comment]
Yea, thanks so much!
